=== UCI-ICTS/icts-dashboard/server/utilities/json_schemas/family.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Family",
    "description": "Schema for the Family table, representing family records including consanguinity and pedigree details.",
    "type": "object",
    "properties": {
      "family_id": {
        "type": "string",
        "description": "Identifier for family (primary key). Needs to be Unique across centers, use participant.gregor_center as ID prefix.",
        "examples": ["CNH-I_fam89052", "UW_CRDR_Family_2"]
      },
      "consanguinity": {
        "type": "string",
        "description": "Indicate if consanguinity is present or suspected within a family",
        "enum": ["None suspected", "Suspected", "Present", "Unknown"]
      },
      "consanguinity_detail": {
        "type": "string",
        "description": "Free text description of any additional consanguinity details",
        "examples": ["Parents are second cousins once removed"]
      },
      "pedigree_file": {
        "type": "string",
        "description": "Name of file (renamed from pedigree_image because it can contain a PED file or image). Pedigree file should be deposited to upload workspace.",
        "examples": [
          "gs://fc-eb352699-d849-483f-aefe-9d35ce2b21ac/FamilyID_CMG_Site_PhsID_ConsentGroup_YYYYMMDD_YXQX.pdf",
          "gs://fc-eb352699-d849-483f-aefe-9d35ce2b21ac/FamilyID_CMG_Site_PhsID_ConsentGroup_YYYYMMDD_YXQX.ped"
        ]
      },
      "pedigree_file_detail": {
        "type": "string",
        "description": "Free text description of other family structure/pedigree file caption or legend. Clarifying purpose: sometimes no PED file is available and the effort involved to encode a full pedigree is high when an image is already available (i.e. legacy publication describing the family).",
        "examples": ["Additional informative family members not sequenced. Sequenced individuals indicated with sample_ID."]
      },
      "family_history_detail": {
        "type": "string",
        "description": "Details about family history that do not fit into structured fields. Family relationship terms should be relative to the proband. Useful if extended family history suggestive of mode of inheritance."
      }
    },
    "required": ["family_id", "consanguinity", "pedigree_file"]
  }

=== UCI-ICTS/icts-dashboard/server/utilities/anvil_json/AnVIL_GREGoR_CNH_I_U06_GRU_family.json
[
    {
        "family_id": "PMGRC-101",
        "consanguinity_detail": "NA",
        "family_history_detail": "Paternal first cousin with toe syndactyly, brother with Noonan syndrome",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-129",
        "consanguinity_detail": "NA",
        "family_history_detail": "sister who died prematurely after being born at 28 weeks, she was less than 2 pounds. Mother is 57yo, has a history of breast cancer diagnosed at 52 to 53 (BRCA1,2 negative). Maternal aunt who is 51yo in the process of getting worked up for breast cancer who has a healthy daughter. Maternal aunt who is 53, who has a son with T1D and a daughter with GI problems. Maternal aunt 55yo who gets migraine headaches who has 2 healthy sons, and a maternal aunt who is 58 years old who has a son who has bipolar disease. Maternal GM died at 74 of heart problems. She had a sister who had breast cancer in her 40s as well as ovarian cancer in her 50s, and a sister had breast cancer diagnosed in her 40s and ovarian cancer in her 50s. Maternal grandfather is 77 years old and has a history of hypertension. Father is 59yo, has diabetes, and hypertension. Paternal grandmother died at 82 after having a stroke in her 20s, and paternal grandfather died of 67 with heart disease and diabetes.",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-136",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-158",
        "consanguinity_detail": "NA",
        "family_history_detail": "non-contributory",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-178",
        "consanguinity_detail": "NA",
        "family_history_detail": "history of febrile seizures in a maternal cousin",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-232",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-251",
        "consanguinity_detail": "NA",
        "family_history_detail": "non-contributory except for Uncle - CP with epilepsy 2/2 brain damage from childhood virus",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-266",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-281",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-316",
        "consanguinity_detail": "NA",
        "family_history_detail": "Paternal grandmother also had imperforate anus and short stature, extensive family history of short stature; mother 5'0, father 5'7''",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-375",
        "consanguinity_detail": "NA",
        "family_history_detail": "father:My cousins on my maternal side-- two have ASD",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-403",
        "consanguinity_detail": "NA",
        "family_history_detail": "Assumption being that mom and dad passed along mutated gene which lead to diagnosis/ Father-My wife and I both have a mutated gene which lead to our son ZSD diagnosis. We unsure at this time who has the PEX1 gene, and who has the other TBD mutated gene.",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-421",
        "consanguinity_detail": "NA",
        "family_history_detail": "unknown",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-459",
        "consanguinity_detail": "NA",
        "family_history_detail": "the couple had 3 first trimester spontaneous pregnancy losses, paternal grandparents had 1 spontaneous pregnancy loss, maternal uncle diagnosed with myotonic muscular dystrophy, but mother tested negative",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-467",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-477",
        "consanguinity_detail": "NA",
        "family_history_detail": "Father had aortic stenosis (Left ventricular outflow tract obstruction) and Paternal GF has Bicuspid Aortic Valve with no complications",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-485",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-509",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-512",
        "consanguinity_detail": "NA",
        "family_history_detail": "maternal grandfather with nystagmus, maternal great grandmother with Parkinsons",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-522",
        "consanguinity_detail": "NA",
        "family_history_detail": "maternal great uncle with intellectual disability lasting into adulthood from unknown cause but without seizure. Paternal second cousin with epilepsy and drop seizures but unknown type",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-525",
        "consanguinity_detail": "NA",
        "family_history_detail": "maternal GF has blood sugar fluctuations when he eats; paternal great uncle with spontaneous kidney \"\"\"\"\"\"\"\"death\"\"\"\"\"\"\"\". Paternal GM has a history of vestibular schwannoma. Paternal uncle and paternal GF are also described as \"\"\"\"\"\"\"\"on the spectrum.\"\"\"\"\"\"\"\" An extended paternal relative had Charcot-Marie-Tooth.",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-538",
        "consanguinity_detail": "NA",
        "family_history_detail": "Maternal history of multiple miscarriages in sisters associated with low progesterone levels. Nephew with a chromosome rearrangement, found to be carried by the father (not blood related to proband)",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-543",
        "consanguinity_detail": "NA",
        "family_history_detail": "none",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-562",
        "consanguinity_detail": "NA",
        "family_history_detail": "paternal GF deceased at 43yo from MVA, HTN, blue sclera",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-572",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-578",
        "consanguinity_detail": "unclear",
        "family_history_detail": "NA",
        "consanguinity": "Present",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-104",
        "consanguinity_detail": "NA",
        "family_history_detail": "non-contributory",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-188",
        "consanguinity_detail": "NA",
        "family_history_detail": "NA",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-204",
        "consanguinity_detail": "NA",
        "family_history_detail": "proband had two full brothers who both had speech therapy. One paternal first-cousin with speech delay",
        "consanguinity": "None suspected",
        "pedigree_file_detail": "NA",
        "pedigree_file": "NA"
    },
    {
        "family_id": "PMGRC-223",
        "consanguinity_detail": "NA",
        "family_history_detail": "maternal aunt epileptic, maternal GM: hypertension, two strokes, blood clots, paternal side: thyroid issues",
